title: eoyount.github.io
author: Eric Yount
email: eoyount@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test space for experimenting with websites.

theme: minima

# social links
twitter_username: eoyount # DO NOT include the @ character, or else the build will fail!
github_username:  eoyount # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
